language: node_js

node_js:
  - "6"

env:
  - NODE_ENV=ci

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g typings"

script:
  - npm test
  - npm run lint
  - npm run build
